//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea.Service_CadeteEnLinea {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:SiteControllerwsdl", ConfigurationName="Service_CadeteEnLinea.SiteControllerPortType")]
    public interface SiteControllerPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#usuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string usuarios(string usuariosJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#usuarios", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> usuariosAsync(string usuariosJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#cadetes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string cadetes(string cadetesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#cadetes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> cadetesAsync(string cadetesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#apoderados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string apoderados(string apoderadoJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#apoderados", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> apoderadosAsync(string apoderadoJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#cadete_apoderado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string cadete_apoderado(string cadete_apoderadoJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#cadete_apoderado", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> cadete_apoderadoAsync(string cadete_apoderadoJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#calificaciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string calificaciones(string calificacionesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#calificaciones", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> calificacionesAsync(string calificacionesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#ingles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string ingles(string inglesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#ingles", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> inglesAsync(string inglesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#asignaturas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string asignaturas(string asignaturasJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#asignaturas", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> asignaturasAsync(string asignaturasJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#notasParciales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string notasParciales(string notasParcialesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#notasParciales", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> notasParcialesAsync(string notasParcialesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#notasFinales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string notasFinales(string notasFinalesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#notasFinales", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> notasFinalesAsync(string notasFinalesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#transacciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string transacciones(string transaccionesJson, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SiteControllerwsdl#transacciones", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> transaccionesAsync(string transaccionesJson, string estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SiteControllerPortTypeChannel : CadeteEnLinea.Service_CadeteEnLinea.SiteControllerPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteControllerPortTypeClient : System.ServiceModel.ClientBase<CadeteEnLinea.Service_CadeteEnLinea.SiteControllerPortType>, CadeteEnLinea.Service_CadeteEnLinea.SiteControllerPortType {
        
        public SiteControllerPortTypeClient() {
        }
        
        public SiteControllerPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteControllerPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteControllerPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteControllerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string usuarios(string usuariosJson, string estado) {
            return base.Channel.usuarios(usuariosJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> usuariosAsync(string usuariosJson, string estado) {
            return base.Channel.usuariosAsync(usuariosJson, estado);
        }
        
        public string cadetes(string cadetesJson, string estado) {
            return base.Channel.cadetes(cadetesJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> cadetesAsync(string cadetesJson, string estado) {
            return base.Channel.cadetesAsync(cadetesJson, estado);
        }
        
        public string apoderados(string apoderadoJson, string estado) {
            return base.Channel.apoderados(apoderadoJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> apoderadosAsync(string apoderadoJson, string estado) {
            return base.Channel.apoderadosAsync(apoderadoJson, estado);
        }
        
        public string cadete_apoderado(string cadete_apoderadoJson, string estado) {
            return base.Channel.cadete_apoderado(cadete_apoderadoJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> cadete_apoderadoAsync(string cadete_apoderadoJson, string estado) {
            return base.Channel.cadete_apoderadoAsync(cadete_apoderadoJson, estado);
        }
        
        public string calificaciones(string calificacionesJson, string estado) {
            return base.Channel.calificaciones(calificacionesJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> calificacionesAsync(string calificacionesJson, string estado) {
            return base.Channel.calificacionesAsync(calificacionesJson, estado);
        }
        
        public string ingles(string inglesJson, string estado) {
            return base.Channel.ingles(inglesJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> inglesAsync(string inglesJson, string estado) {
            return base.Channel.inglesAsync(inglesJson, estado);
        }
        
        public string asignaturas(string asignaturasJson, string estado) {
            return base.Channel.asignaturas(asignaturasJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> asignaturasAsync(string asignaturasJson, string estado) {
            return base.Channel.asignaturasAsync(asignaturasJson, estado);
        }
        
        public string notasParciales(string notasParcialesJson, string estado) {
            return base.Channel.notasParciales(notasParcialesJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> notasParcialesAsync(string notasParcialesJson, string estado) {
            return base.Channel.notasParcialesAsync(notasParcialesJson, estado);
        }
        
        public string notasFinales(string notasFinalesJson, string estado) {
            return base.Channel.notasFinales(notasFinalesJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> notasFinalesAsync(string notasFinalesJson, string estado) {
            return base.Channel.notasFinalesAsync(notasFinalesJson, estado);
        }
        
        public string transacciones(string transaccionesJson, string estado) {
            return base.Channel.transacciones(transaccionesJson, estado);
        }
        
        public System.Threading.Tasks.Task<string> transaccionesAsync(string transaccionesJson, string estado) {
            return base.Channel.transaccionesAsync(transaccionesJson, estado);
        }
    }
}
