//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class apoderado
    {
        public apoderado()
        {
            this.cadete_apoderado = new HashSet<cadete_apoderado>();
        }
    
        public decimal rut { get; set; }
        public string direccion { get; set; }
        public string comuna { get; set; }
        public string ciudad { get; set; }
        public string fono { get; set; }
        public string fonoComercial { get; set; }
        public string difunto { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<cadete_apoderado> cadete_apoderado { get; set; }
    }
}
