//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignatura
    {
        public asignatura()
        {
            this.notas_finales = new HashSet<notas_finales>();
            this.notas_parciales = new HashSet<notas_parciales>();
        }
    
        public int idasignatura { get; set; }
        public string codigo { get; set; }
        public Nullable<decimal> ano { get; set; }
        public Nullable<decimal> semestre { get; set; }
        public Nullable<decimal> curso { get; set; }
        public string nombre { get; set; }
        public string especialidad { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<notas_finales> notas_finales { get; set; }
        public virtual ICollection<notas_parciales> notas_parciales { get; set; }
    }
}
