//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadete_apoderado
    {
        public int idcadete_apoderado { get; set; }
        public decimal cadete_rut { get; set; }
        public decimal apoderado_rut { get; set; }
        public string tipoApoderado { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual apoderado apoderado { get; set; }
        public virtual cadete cadete { get; set; }
    }
}
