//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadete
    {
        public cadete()
        {
            this.cadete_apoderado = new HashSet<cadete_apoderado>();
            this.calificaciones = new HashSet<calificaciones>();
            this.ingles_tae = new HashSet<ingles_tae>();
            this.notas_finales = new HashSet<notas_finales>();
            this.notas_parciales = new HashSet<notas_parciales>();
            this.transaccion = new HashSet<transaccion>();
        }
    
        public decimal rut { get; set; }
        public Nullable<decimal> nCadete { get; set; }
        public string division { get; set; }
        public Nullable<decimal> anoIngreso { get; set; }
        public Nullable<decimal> anoNacimiento { get; set; }
        public Nullable<decimal> mesNacimiento { get; set; }
        public Nullable<decimal> diaNacimiento { get; set; }
        public string lugarNacimiento { get; set; }
        public string seleccion { get; set; }
        public string especialidad { get; set; }
        public string nivel { get; set; }
        public string curso { get; set; }
        public string circulo { get; set; }
        public string nacionalidad { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<cadete_apoderado> cadete_apoderado { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<calificaciones> calificaciones { get; set; }
        public virtual ICollection<ingles_tae> ingles_tae { get; set; }
        public virtual ICollection<notas_finales> notas_finales { get; set; }
        public virtual ICollection<notas_parciales> notas_parciales { get; set; }
        public virtual ICollection<transaccion> transaccion { get; set; }
    }
}
