//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones
    {
        public int idcalificaciones { get; set; }
        public Nullable<decimal> cadete_rut { get; set; }
        public Nullable<decimal> ano { get; set; }
        public Nullable<decimal> semestre { get; set; }
        public Nullable<decimal> mando { get; set; }
        public Nullable<decimal> interes_profesional { get; set; }
        public Nullable<decimal> personalidad_madurez { get; set; }
        public Nullable<decimal> responsabilidad { get; set; }
        public Nullable<decimal> espiritu_militar { get; set; }
        public Nullable<decimal> cooperacion { get; set; }
        public Nullable<decimal> conducta { get; set; }
        public Nullable<decimal> aptitud_fisica { get; set; }
        public Nullable<decimal> tenida_orden_aseo { get; set; }
        public Nullable<decimal> final { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual cadete cadete { get; set; }
    }
}
