//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class errores
    {
        public int iderror { get; set; }
        public string codigo { get; set; }
        public Nullable<int> idRegistro { get; set; }
        public string tabla { get; set; }
        public string error { get; set; }
        public Nullable<int> tarea_idTarea { get; set; }
    
        public virtual tarea tarea { get; set; }
    }
}
