//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingles_tae
    {
        public int idingles_tae { get; set; }
        public Nullable<decimal> cadete_rut { get; set; }
        public Nullable<decimal> mes { get; set; }
        public Nullable<decimal> ano { get; set; }
        public Nullable<decimal> speaking { get; set; }
        public Nullable<decimal> understanding { get; set; }
        public Nullable<decimal> writing { get; set; }
        public Nullable<decimal> average { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual cadete cadete { get; set; }
    }
}
