//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccion
    {
        public int idtransaccion { get; set; }
        public Nullable<decimal> cadete_rut { get; set; }
        public string tipoTransaccion { get; set; }
        public Nullable<int> monto { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
        public string descripcion { get; set; }
        public string tipoCuenta { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual cadete cadete { get; set; }
    }
}
