//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeteEnLinea
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public decimal rut { get; set; }
        public string apellidoPat { get; set; }
        public string apellidoMat { get; set; }
        public string nombre { get; set; }
        public string password_2 { get; set; }
        public string perfil { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual apoderado apoderado { get; set; }
        public virtual cadete cadete { get; set; }
    }
}
